[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mloda"
version = "0.0.1"
description = "Rethinking Data and Feature Engineering"
readme = { file = "README.md", content-type = "text/markdown" }
license = { file = "LICENSE.TXT" }
authors = [
    { name = "Tom Kaltofen", email = "mloda.info@gmail.com" }
]
dependencies = [
    "pyarrow"
]

requires-python = ">=3.8"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3"
]

[project.urls]
"Bug Tracker" = "https://github.com/TomKaltofen/mloda/issues"
"Documentation" = "https://tomkaltofen.github.io/mloda/"
"Source Code" = "https://github.com/TomKaltofen/mloda"
"PyPI" = "https://pypi.org/project/mloda/"
"Homepage" = "https://github.com/TomKaltofen/mloda"

[tool.setuptools]
packages = { find = { include = ["mloda_core*", "mloda_plugins*"] } }
include-package-data = true

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
