site_name: mloda docs
nav:
  - Home: 
    - index.md
  - Introduction Notebooks:
    - Basics:
      - Table of Content: examples/mloda_basics/0_table_of_content.ipynb
      - Intro to the core interfaces of mloda: examples/mloda_basics/1_ml_mloda_intro.ipynb
      - What makes mloda unique: examples/mloda_basics/2_ml_advantage_process_focus.ipynb
      - Data, Feature, FeatureSets and FeatureGroups in mloda: examples/mloda_basics/3_ml_data_feature_feature_groups.ipynb
      - Data Producer, User, Owner in mloda: examples/mloda_basics/4_ml_data_producers_user_owner.ipynb
  - Getting Started:
    - Installation: chapter1/installation.md
    - API Request: chapter1/api-request.md
    - Feature Groups: chapter1/feature-groups.md
    - Compute Frameworks: chapter1/compute-frameworks.md
    - Extender: chapter1/extender.md
  - In Depth - Basics:
    - mloda API: in_depth/mloda-api.md
    - (Feature) data: in_depth/access-feature-data.md
    - Join data: in_depth/join_data.md
    - Filter data: in_depth/filter_data.md
    - Artifacts: in_depth/artifacts.md
  - In Depth - Advanced:
    - Data quality: in_depth/data-quality.md
    - Domain concept: in_depth/domain.md
    
  - Development:
    - Contributers: development.md
    - License - Apache 2.0: license.md
    - Missing: missing.md
  - Need Help?:
    - FAQ: faq.md
    - Need Help: need-help.md

  # todo
  #- ComputeFrameworkTransformMap in Depth: need-help.md
  #- Data Quality in Depth: need-help.md
  #- License in Depth: need-help.md
  #- Feature in Depth
  #- Feature Groups in Depth: need-help.md
  #- Compute Frameworks in Depth: need-help.md
  #- Extender in Depth: need-help.md

theme:
  name: readthedocs

plugins:
  - mkdocs-jupyter:
      include: ["*.ipynb"] 
      execute: false
